# Generated by Django 6.0.3 on 2026-04-03 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_website_professor_lab_link_professor_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='designation',
            field=models.CharField(default='Professor', max_length=100),
        ),
        migrations.AddField(
            model_name='professor',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
