# Generated by Django 6.0.3 on 2026-04-03 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_professor_user_professorupdaterequest_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
