# Generated by Django 6.0.3 on 2026-04-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_profileclaimrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='lab_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='lab_image',
            field=models.ImageField(blank=True, null=True, upload_to='lab_images/'),
        ),
        migrations.AddField(
            model_name='professor',
            name='lab_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='publications',
            field=models.TextField(blank=True, help_text='আপনার পাবলিকেশনগুলোর লিস্ট দিন (প্রতিটি নতুন লাইনে)'),
        ),
        migrations.AddField(
            model_name='professor',
            name='uni_website',
            field=models.URLField(blank=True, help_text='ইউনিভার্সিটির ওয়েবসাইটের লিংক', null=True),
        ),
    ]
