# Generated by Django 6.0.3 on 2026-04-06 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='domestic_deadline',
            field=models.CharField(blank=True, help_text='Example: Fall - Dec 15, Spring - Oct 1', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='international_deadline',
            field=models.CharField(blank=True, help_text='Example: Fall - Dec 1, Spring - Sep 15', max_length=255, null=True),
        ),
    ]
