# Generated by Django 6.0.3 on 2026-04-06 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_university_domestic_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='domestic_deadline_date',
            field=models.DateField(blank=True, help_text='ডোমেস্টিক ডেডলাইনের সঠিক তারিখ দিন', null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='intl_deadline_date',
            field=models.DateField(blank=True, help_text='ইন্টারন্যাশনাল ডেডলাইনের সঠিক তারিখ দিন', null=True),
        ),
    ]
