# Generated by Django 6.0.3 on 2026-04-06 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_university_domestic_deadline_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('wrong_email', 'ভুল ইমেইল অ্যাড্রেস'), ('wrong_deadline', 'ভুল ডেডলাইন'), ('left_uni', 'ইউনিভার্সিটি ছেড়ে দিয়েছেন'), ('spam', 'ফেক প্রোফাইল বা স্প্যাম'), ('other', 'অন্যান্য সমস্যা')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='main_app.professor')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
