# Generated by Django 6.0.3 on 2026-04-06 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='status',
            field=models.CharField(choices=[('saved', 'To Review (দেখতে হবে)'), ('emailed', 'Email Sent (ইমেইল পাঠিয়েছি)'), ('interview', 'Interviewing (ইন্টারভিউ চলছে)'), ('accepted', 'Accepted (অ্যাকসেপ্টেড)'), ('rejected', 'Rejected (রিজেক্টেড)')], default='saved', max_length=20),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.professor'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
