# Generated by Django 6.0.3 on 2026-07-30 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_bookmark_status_alter_bookmark_professor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='country',
        ),
        migrations.RemoveField(
            model_name='university',
            name='domestic_deadline',
        ),
        migrations.RemoveField(
            model_name='university',
            name='domestic_deadline_date',
        ),
        migrations.RemoveField(
            model_name='university',
            name='international_deadline',
        ),
        migrations.RemoveField(
            model_name='university',
            name='intl_deadline_date',
        ),
        migrations.AddField(
            model_name='university',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=150)),
                ('deadline', models.DateField()),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='main_app.university')),
            ],
        ),
    ]
