# Generated by Django 6.0.3 on 2026-07-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_remove_university_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='location',
        ),
        migrations.AddField(
            model_name='university',
            name='country',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university',
            name='domestic_deadline',
            field=models.CharField(blank=True, help_text='Example: Fall - Dec 15, Spring - Oct 1', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='domestic_deadline_date',
            field=models.DateField(blank=True, help_text='ডোমেস্টিক ডেডলাইনের সঠিক তারিখ দিন', null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='international_deadline',
            field=models.CharField(blank=True, help_text='Example: Fall - Dec 1, Spring - Sep 15', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='intl_deadline_date',
            field=models.DateField(blank=True, help_text='ইন্টারন্যাশনাল ডেডলাইনের সঠিক তারিখ দিন', null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Program',
        ),
    ]
