# Generated by Django 6.0.3 on 2026-07-31 01:10

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_remove_university_location_university_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
