# Generated by Django 6.0.3 on 2026-07-31 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_university_location_alter_university_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professorupdaterequest',
            name='requested_changes',
            field=models.TextField(help_text='কী পরিবর্তন করতে চান তা বিস্তারিত লিখুন'),
        ),
    ]
