# Generated by Django 6.0.3 on 2026-08-01 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_otpverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='domestic_deadline',
        ),
        migrations.RemoveField(
            model_name='university',
            name='domestic_deadline_date',
        ),
        migrations.RemoveField(
            model_name='university',
            name='international_deadline',
        ),
        migrations.RemoveField(
            model_name='university',
            name='intl_deadline_date',
        ),
        migrations.AddField(
            model_name='university',
            name='fall_dom_deadline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='fall_intl_deadline',
            field=models.CharField(blank=True, help_text='Example: Dec 15, 2026 or Rolling', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='spring_dom_deadline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='spring_intl_deadline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='SubjectDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Example: Computer Science, Mechanical Engineering', max_length=200)),
                ('fall_deadline', models.CharField(blank=True, max_length=100, null=True)),
                ('spring_deadline', models.CharField(blank=True, max_length=100, null=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='main_app.university')),
            ],
        ),
    ]
