# Generated by Django 6.0.3 on 2026-08-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_remove_university_domestic_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectdeadline',
            name='degree_level',
            field=models.CharField(choices=[('phd', 'PhD'), ('masters', 'Masters'), ('bachelors', 'Bachelors')], default='phd', help_text='ডিগ্রির ধরন সিলেক্ট করুন', max_length=20),
        ),
        migrations.AddField(
            model_name='subjectdeadline',
            name='priority_deadline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subjectdeadline',
            name='summer_deadline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subjectdeadline',
            name='name',
            field=models.CharField(help_text='Example: Computer Science', max_length=200),
        ),
    ]
