# Generated by Django 6.0.3 on 2026-08-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_subjectdeadline_degree_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectdeadline',
            name='is_domestic',
            field=models.BooleanField(default=True, help_text='এটি কি ডোমেস্টিক ডেডলাইনের জন্য প্রযোজ্য?'),
        ),
        migrations.AddField(
            model_name='subjectdeadline',
            name='is_international',
            field=models.BooleanField(default=True, help_text='এটি কি ইন্টারন্যাশনাল ডেডলাইনের জন্য প্রযোজ্য?'),
        ),
        migrations.AddField(
            model_name='subjectdeadline',
            name='program_type',
            field=models.CharField(choices=[('on_campus', 'On-Campus'), ('online', 'Online Program')], default='on_campus', help_text='প্রোগ্রামের ধরন', max_length=20),
        ),
        migrations.AlterField(
            model_name='subjectdeadline',
            name='degree_level',
            field=models.CharField(choices=[('phd', 'PhD'), ('masters', 'Masters'), ('bachelors', 'Bachelors'), ('certificate', 'Certificate')], default='phd', help_text='ডিগ্রির ধরন সিলেক্ট করুন', max_length=20),
        ),
    ]
