# Generated by Django 6.0.3 on 2026-08-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_subjectdeadline_is_domestic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectdeadline',
            name='fall_deadline',
        ),
        migrations.RemoveField(
            model_name='subjectdeadline',
            name='is_domestic',
        ),
        migrations.RemoveField(
            model_name='subjectdeadline',
            name='is_international',
        ),
        migrations.RemoveField(
            model_name='subjectdeadline',
            name='spring_deadline',
        ),
        migrations.RemoveField(
            model_name='subjectdeadline',
            name='summer_deadline',
        ),
        migrations.AddField(
            model_name='subjectdeadline',
            name='fall_dom_deadline',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fall (Domestic)'),
        ),
        migrations.AddField(
            model_name='subjectdeadline',
            name='fall_intl_deadline',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fall (International)'),
        ),
        migrations.AddField(
            model_name='subjectdeadline',
            name='spring_dom_deadline',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Spring (Domestic)'),
        ),
        migrations.AddField(
            model_name='subjectdeadline',
            name='spring_intl_deadline',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Spring (International)'),
        ),
        migrations.AddField(
            model_name='subjectdeadline',
            name='summer_dom_deadline',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Summer (Domestic)'),
        ),
        migrations.AddField(
            model_name='subjectdeadline',
            name='summer_intl_deadline',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Summer (International)'),
        ),
        migrations.AlterField(
            model_name='subjectdeadline',
            name='priority_deadline',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Priority Deadline'),
        ),
    ]
