# Generated by Django 6.0.3 on 2026-08-04 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_remove_subjectdeadline_fall_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectdeadline',
            name='is_certificate',
            field=models.BooleanField(default=False, help_text='এটি কি একটি সার্টিফিকেট কোর্স?'),
        ),
        migrations.AlterField(
            model_name='subjectdeadline',
            name='degree_level',
            field=models.CharField(choices=[('phd', 'PhD'), ('masters', 'Masters'), ('bachelors', 'Bachelors')], default='phd', help_text='ডিগ্রির ধরন সিলেক্ট করুন', max_length=20),
        ),
    ]
