# Generated by Django 6.0.3 on 2026-08-04 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_subjectdeadline_is_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='university_logos/'),
        ),
    ]
