# Generated by Django 6.0.3 on 2026-08-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_university_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(help_text='Ex: Application Guide, Communication, Success Story', max_length=100)),
                ('summary', models.TextField(help_text='Short description for the card')),
                ('read_time', models.IntegerField(help_text='Reading time in minutes')),
                ('views', models.DecimalField(decimal_places=1, help_text='Ex: 1.2, 3.4 for k views', max_digits=5)),
                ('author_image', models.ImageField(blank=True, null=True, upload_to='article_authors/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
