# Generated by Django 6.0.3 on 2026-08-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Upload an image for card background (Optional)', null=True, upload_to='article_bgs/'),
        ),
    ]
