# Generated by Django 6.0.3 on 2026-08-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_article_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, help_text='Full text of the article', null=True),
        ),
    ]
