# Generated by Django 6.0.3 on 2026-08-06 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_alter_article_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='short_name',
            field=models.CharField(blank=True, help_text='যেমন: MIT, LPU, ISM', max_length=20, null=True),
        ),
    ]
